# NumPy Learning

In [3]:
pip install -r requirements.txt

Note: you may need to restart the kernel to use updated packages.


In [4]:
import numpy as np

## Arrays

In [5]:
# Array
a = np.array([1, 2, 3, 4, 5, 6])
print(a)

[1 2 3 4 5 6]


In [6]:
a = np.array([[1, 2, 3, 4], [5, 6, 7, 8], [9, 10, 11, 12]])
print(a)
a[2,2]

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]


11

In [7]:
np.zeros(2)

array([0., 0.])

In [8]:
np.ones(2)

array([1., 1.])

In [9]:
np.empty(5) 

array([4.63829075e-310, 0.00000000e+000, 4.63941331e-310, 4.63941330e-310,
       3.16202013e-322])

In [10]:
np.arange(66)

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33,
       34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50,
       51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64, 65])

In [11]:
np.arange(50) + 1

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33, 34,
       35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50])

In [12]:
np.arange(50) * 2

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18, 20, 22, 24, 26, 28, 30, 32,
       34, 36, 38, 40, 42, 44, 46, 48, 50, 52, 54, 56, 58, 60, 62, 64, 66,
       68, 70, 72, 74, 76, 78, 80, 82, 84, 86, 88, 90, 92, 94, 96, 98])

In [13]:
np.arange(50) / 2

array([ 0. ,  0.5,  1. ,  1.5,  2. ,  2.5,  3. ,  3.5,  4. ,  4.5,  5. ,
        5.5,  6. ,  6.5,  7. ,  7.5,  8. ,  8.5,  9. ,  9.5, 10. , 10.5,
       11. , 11.5, 12. , 12.5, 13. , 13.5, 14. , 14.5, 15. , 15.5, 16. ,
       16.5, 17. , 17.5, 18. , 18.5, 19. , 19.5, 20. , 20.5, 21. , 21.5,
       22. , 22.5, 23. , 23.5, 24. , 24.5])

In [14]:
np.arange(1, 9) + 1


array([2, 3, 4, 5, 6, 7, 8, 9])

In [15]:
np.linspace(0, 10, num=6)

array([ 0.,  2.,  4.,  6.,  8., 10.])

## Adding, removing, and sorting elements

In [16]:
arr = np.array([2, 1, 5, 3, 7, 4, 6, 8])
np.sort(arr)

array([1, 2, 3, 4, 5, 6, 7, 8])

In [17]:
a = np.array([1, 2, 3, 4])
b = np.array([5, 6, 7, 8])
np.concatenate((a, b))

array([1, 2, 3, 4, 5, 6, 7, 8])

In [18]:
x = np.array([[1, 2], [7, 6]])
y = np.array([[5, 6]])
np.concatenate((x,y))

array([[1, 2],
       [7, 6],
       [5, 6]])

In [26]:
np.zeros((99999,99999), dtype='int64')

MemoryError: Unable to allocate 74.5 GiB for an array with shape (99999, 99999) and data type int64

In [30]:
np.identity(200000)

MemoryError: Unable to allocate 298. GiB for an array with shape (200000, 200000) and data type float64